### ISSUE TITLE
【dev】事業所詳細データをcomponents配下のvueで取得したい

### ISSUE THREAD

**Issue by watasho358** [koki-takishita/home-care-navi-front#46]
- _id.vueでaxios通信をして事業所詳細データを取得し、mountedメソッドでページを読み込んだタイミングでstoreに保存
- office.jsでstate→action→mutationsの工程を得てgettersで取得
- OfficesRightCard.vueでgettersで取得

エラー：`Module build failed (from ./node_modules/babel-loader/lib/index.js): SyntaxError: /Users/watasho/job/home-care-navi-front/pages/offices/_id.vue:〜〜〜`

pages/offices/_id.vue
```
import { mapActions } from 'vuex'
export default {
layout: 'application',
  async asyncData({ $axios, params }) {
    let office = []
    const id = `${params.id}`
    await $axios.$get(`offices/${id}`).then((res) => (office = res))

    return { office }
  },

mounted:{
    addOfficeData()
  },

  methods: {
    ...mapActions('office', ['addOfficeDetailAction']),

    addOfficeData() {
      this.addOfficeDetailAction({
        office: this.office
      })
    },
  },
}
```

store/office.js
```
export const state = () => ({
    office: [],
})

export const getters = {
    getOffice: (state) => state.office
}

export const mutations = {
    getOfficeDetail(state, office) {
        state.office = office
    }
}

export const actions = {
    addOfficeDetailAction({ commit }, office) {
        commit('getOfficeDetail', office)
    },
}
```

components/OfficesRightCard.vue
```
<script>
import { mapGetters } from 'vuex'
export default {
  data() {
    return{
      office: []
    }
  },
  computed:{
     ...mapGetters('office', ['getOffice']),
  },
  watch: {
    getOffice() {
      this.office = this.getOffice
    },
  },
}
</script>
```

**Comment by watasho358** [comment]
getリクエストを送った後にストアにコミットしてみる
```
async asyncData({ $axios, params }) {
    let office = []
    const id = `${params.id}`
    await $axios.$get(`offices/${id}`).then((res) => (office = res))
    store.commit('office/addOfficeDetailAction', office)
    return { office }
  },
watch: {
    emptyState() {
      this.msgs = this.getMsg
    },
  },
```
TypeError
`Cannot read properties of undefined (reading 'status')`

**Comment by watasho358** [comment]
dockerが起動していなかったので起動させて再度アクセスする。
` ERROR  [vuex] unknown mutation type: office/addOfficeDetail`

**Comment by koki-takishita** [comment]
このissueって今動いているやつを改善したいという意味で開いてるやつですか？

**Comment by watasho358** [comment]
そうですね。コードを分割して見やすくして改善したいという意味です。フロントの動きは変わりませんが

**Comment by koki-takishita** [comment]
OKですー、今取り組んでるTOPページはVuexで行ってます。
やっていることは似てる気がするので共有のときにでも、詰まってる箇所があれば教えてくださると解決するかもしれません

下記なんとなんとなく、似てそうだと思った処理
ページロード、リロード時に値をセットする。(TOPページでは関東・東京都でデータセット)
コードレベルだとわからんと思うので、流れ的にはこんな感じでやってます
1. mounted()でVuexのアクション呼び出すメソッド発火
2. Vuex内でAPI叩いて、データ取得
3. stateに箱にデータ入れる
4. watchでデータの更新を監視
5. 更新されたのを検知したら、componentのdataにstateの値を入れる
