### ISSUE TITLE
【wait】header開いた状態でログアウトすると、ログアウトメッセージが隠れる

### ISSUE THREAD

**Issue by koki-takishita** [koki-takishita/home-care-navi-front#64]
[loom:現状の挙動](https://www.loom.com/share/615f8698ff8f4a41ac6ee62928bdf24d)
## 問題点
- header開いた状態でログアウトすると、フラッシュメッセージが隠れてしまう
### xdにないため、デザイン決めてないけど本当にこれで良いのか？
- 幅
- 色(ログイン・ログアウトそれぞれ同じ色で良い？)
- 表示位置(画面上部)
- 消し方(遷移しても残る)

**Comment by suwonkun** [comment]
ボタンの表示が切り替わっているので、ログアウトできたと認識できると思います。なので、そのままでいいと思いますよ。

**Comment by watasho358** [comment]
- 隠れるのはそのままでいい
- 文章量に対して幅が広すぎるので、それの半分くらいにして、テキストも中央にする
- 色は赤以外で緑とか青系のさっぱりした色ならなんでも
- 遷移したら消えるようにしたい

**Comment by koki-takishita** [comment]
> * 文章量に対して幅が広すぎるので、それの半分くらいにして、テキストも中央にする

ログイン・ログアウトの他にも、様々なエラーをキャッチするので、これ対応しようと思うと文字数によって幅を変更するということですか？
これとか
[![Image from Gyazo](https://i.gyazo.com/251273d586f9dd0b539a5496c0ef6c91.png)](https://gyazo.com/251273d586f9dd0b539a5496c0ef6c91)

> *幅は画面いっぱい使うけどテキストは中央とか
画面中央のサイトとか参考サイトありますかね？
左詰めが多いのかなーと勝手に思っていたので、中央の方が主流なのかな？

**Comment by watasho358** [comment]
エラーメッセージのこと考慮してませんでした。
文字数によって幅を変えるのは統一感なくて実装も大変そうなので、幅はやっぱり変えなくていいと思います。
調べたところ、左詰めが主流で、あまり中央にしてるのはなかったです。
中央にすると、改行したときも中央になって読みづらくなりそう

**Comment by koki-takishita** [comment]
> エラーメッセージのこと考慮してませんでした。 文字数によって幅を変えるのは統一感なくて実装も大変そうなので、幅はやっぱり変えなくていいと思います。 調べたところ、左詰めが主流で、あまり中央にしてるのはなかったです。 中央にすると、改行したときも中央になって読みづらくなりそう

了解です
共有の時に決めましょう
