### ISSUE TITLE
【wait】フラッシュメッセージのコンポーネントの名前が適切でない

### ISSUE THREAD

**Issue by koki-takishita** [koki-takishita/home-care-navi-front#65]
## 現状
- フラッシュメッセージのコンポーネントの名前は下記のとおりである
`components/ErrorMsg.vue`
- 挙動
機能としては、下記のようにリクエスト成功・失敗時にメッセージを表示してくれる
[挙動の動画](https://www.loom.com/share/0d7c6155073848d489af9c9592ef7f34)
## 問題点
- 名前が適切でない
下記のような名前だとエラーメッセージのみを連想するが、成功メッセージも表示するため表現として正確でない
`components/ErrorMsg.vue`
## 解決策
- 名前を失敗・成功両方含んだ適切な名前に変更する
## 議論したいこと
- 適切な名前はどんな名前がいいと思うか？

**Comment by watasho358** [comment]
同じくFlashMsg.vueで
