### ISSUE TITLE
【dev】事業所詳細画面レイアウト問題

### ISSUE THREAD

**Issue by watasho358** [koki-takishita/home-care-navi-front#84]
- XDと全体の比率が違う

![image](https://user-images.githubusercontent.com/34031637/170045958-12ca916e-8cdd-44b8-9b12-2a744ebdbfd0.png)
![image](https://user-images.githubusercontent.com/34031637/170046060-4e82d4f3-457a-4489-8be4-97878e603eb8.png)

- 開発画面では、カードとカードの間にわずかな隙間ができちゃっている
![image](https://user-images.githubusercontent.com/34031637/170046391-c7d1e8c8-75c2-4748-ae96-d770cd89f2ca.png)
![image](https://user-images.githubusercontent.com/34031637/170046764-09bea783-c84b-47fb-992a-777329d038c4.png)

**Comment by koki-takishita** [comment]
これdev案件
