### ISSUE TITLE
【dev】スタッフ登録画面の画像フォームの幅が広い

### ISSUE THREAD

**Issue by watasho358** [koki-takishita/home-care-navi-front#85]
# 問題点
ラベルの「画像をアップロードする」の文字の幅と同じくらいで、フォームの下線の幅も同じにしたほうがいいという意見が出た。
![image](https://user-images.githubusercontent.com/34031637/170141787-4b26545e-d212-4131-8eec-857dab5023b4.png)
# 対策およびその結果

- フォームの幅をグリッドシステムで短くしたが、画面を狭めたときにエラーメッセージが収まりきらずに改行される

- エラーメッセージを短くすれば対応できそうだが、要相談

![image](https://user-images.githubusercontent.com/34031637/170143056-859611b0-e1d4-45d0-a44c-e876bf90959b.png)

- スマホサイズでは確実に改行される

![image](https://user-images.githubusercontent.com/34031637/170143251-1735d7ae-972f-4155-b3e4-8a3fcc619b15.png)

**Comment by koki-takishita** [comment]
[![Image from Gyazo](https://i.gyazo.com/162bbb08877d43211b26c3b6c70c4825.png)](https://gyazo.com/162bbb08877d43211b26c3b6c70c4825)

**Comment by koki-takishita** [comment]
[example](https://codepen.io/koki-takishita/pen/bGLoyOV)
[![Image from Gyazo](https://i.gyazo.com/b60240e8d1789aa889c6c91ac7eb337d.gif)](https://gyazo.com/b60240e8d1789aa889c6c91ac7eb337d)

**Comment by watasho358** [comment]
そこだけグリッド使わないで直接幅を狭めればいけそうな気がします。グリッドを全体に適用させているせいで、サイズを直接いじってもグリッドが優先されるみたいなので

**Comment by watasho358** [comment]
表示崩れだけが問題ですが

**Comment by koki-takishita** [comment]
> 表示崩れだけが問題ですが

`表示崩れ`これ状況わからないです。
例を見せてもらえますか？

**原則9時30以降でOKです**
業務時間内だと足らないので個人的にやってるだけなので、業務時間外はすぐに返さなくても大丈夫です

**Comment by koki-takishita** [comment]
これdev案件

**Comment by watasho358** [comment]
＼(^o^)／
![image](https://user-images.githubusercontent.com/34031637/170157149-dc9e970d-d49d-4c2b-a879-c33dc53b4a49.png)

**Comment by koki-takishita** [comment]
下の感じで、アップロードするが見きれない程度でいきましょう
[![Image from Gyazo](https://i.gyazo.com/2ce61c553974480deaabb5fe27f1fa0b.png)](https://gyazo.com/2ce61c553974480deaabb5fe27f1fa0b)

**Comment by watasho358** [comment]
解決できたので、このissueは閉じます。ご協力ありがとうございました
![image](https://user-images.githubusercontent.com/34031637/170165120-c12b2489-011c-4956-bb1a-b25a7e52c1df.png)
![image](https://user-images.githubusercontent.com/34031637/170165237-f8cfb0d6-df71-492c-ad32-ef295da19f6a.png)
