### ISSUE TITLE
【help】ログイン後のページ遷移の設定

### ISSUE THREAD

**Issue by suwonkun** [koki-takishita/home-care-navi-front#89]
@watasho358 @koki-takishita @tmhr0 
**やること**
ケアマネージャーのログイン後に予約一覧画面に遷移する

**問題点**
予約一覧画面のURLはoffices/:id/appoiments/でオフィスに紐付いているため、ケアマネージャーがオフィスを登録していない状態で遷移するURLの設定ができないです。

**解決策**
自分なりに考えた解決策は、オフィスを登録してない場合のページ（事業所を登録してください的な）を作成する。

その他意見あれば伺いたいです

**Comment by koki-takishita** [comment]
今回のタスクで言えば、それは考えるはまだ先の話なので考えなくて良いです.

質問に回答するなら下記の感じなるかな この方が自然な気がする
- officeある
予約一覧ページ
- officeない
office新規登録ページ
